"""The blackboard -- Class 7's "not optional" surface.

Everything the agent decides is written here BEFORE it touches the tree: what it
scored and why, the exact prompt it issued, and the bytes it got back. The point is
not debugging. It is that a human can read the record afterwards and say whether the
agent did what was intended, without having to trust a summary the agent wrote about
itself.

Two sinks, always both:

  - the console, so the run is watchable live
  - `runs/<stamp>/blackboard.md`, so it survives the terminal

Prompts and generated bytes also land as their own files under the run directory.
They are the two artifacts a summary is least trustworthy about -- a paraphrased
prompt is not the prompt that was sent -- so they are recorded verbatim and the
markdown links to them rather than inlining them.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Blackboard:
    run_dir: Path
    echo: bool = True
    _lines: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.run_dir.mkdir(parents=True, exist_ok=True)
        (self.run_dir / "prompts").mkdir(exist_ok=True)
        (self.run_dir / "generated").mkdir(exist_ok=True)

    # -- writing ----------------------------------------------------------

    def _emit(self, text: str) -> None:
        self._lines.append(text)
        if self.echo:
            # The GDD is full of section signs and typographic dashes and they reach
            # here through quoted invariant text. A Windows console on cp1252 raises
            # UnicodeEncodeError on those rather than mangling them, which would kill
            # a run for a reason that has nothing to do with the run.
            sys.stdout.write(text.encode("utf-8", "replace").decode("utf-8", "replace") + "\n")
            sys.stdout.flush()
        self.flush()

    def flush(self) -> None:
        (self.run_dir / "blackboard.md").write_text(
            "\n".join(self._lines) + "\n", encoding="utf-8"
        )

    def header(self, text: str) -> None:
        self._emit(f"\n## {text}\n")

    def section(self, text: str) -> None:
        self._emit(f"\n### {text}\n")

    def say(self, text: str) -> None:
        self._emit(text)

    def bullet(self, text: str) -> None:
        self._emit(f"- {text}")

    def table(self, headers: list[str], rows: list[list[str]]) -> None:
        self._emit("")
        self._emit("| " + " | ".join(headers) + " |")
        self._emit("|" + "|".join("---" for _ in headers) + "|")
        for r in rows:
            self._emit("| " + " | ".join(str(c) for c in r) + " |")
        self._emit("")

    # -- verbatim artefacts -----------------------------------------------

    def record_prompt(self, name: str, system: str, user: str) -> Path:
        """The exact bytes sent to the model. Recorded before the call, so a run that
        dies mid-call still shows what it was asking for."""
        path = self.run_dir / "prompts" / f"{name}.md"
        path.write_text(
            f"# SYSTEM\n\n{system}\n\n# USER\n\n{user}\n", encoding="utf-8"
        )
        self.bullet(f"prompt issued -> `{path.relative_to(self.run_dir)}` "
                    f"({len(system) + len(user)} chars)")
        return path

    def record_generated(self, name: str, text: str) -> Path:
        """What the model produced, before anything is written into the tree. This is
        the copy the acceptance diff is taken against."""
        path = self.run_dir / "generated" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        self.bullet(f"generated -> `{path.relative_to(self.run_dir)}` ({len(text)} bytes)")
        return path

    def record_json(self, name: str, payload: object) -> Path:
        path = self.run_dir / f"{name}.json"
        path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
        return path
